# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#   coding: utf-8


AgeClass.destroy_all
AgeClass.create(:name => '小学生')
AgeClass.create(:name => '中学生')
AgeClass.create(:name => '高校生')
AgeClass.create(:name => '大学生')
AgeClass.create(:name => '社会人(10代)')
AgeClass.create(:name => '社会人(20代)')
AgeClass.create(:name => '社会人(30代)')
AgeClass.create(:name => '社会人(40代)')
AgeClass.create(:name => '社会人(50代以上)')

District.destroy_all
District.create(:name => '東北')
District.create(:name => '関東')
District.create(:name => '中部')
District.create(:name => '北陸')
District.create(:name => '関西')
District.create(:name => '中国')
District.create(:name => '四国')
District.create(:name => '九州')
District.create(:name => '沖縄・北海道')

Hand.destroy_all
Hand.create(:name => '右')
Hand.create(:name => '左')

Gender.destroy_all
Gender.create(:name => '男')
Gender.create(:name => '女')

Field.destroy_all
Field.create(:name => '自陣右')
Field.create(:name => '自陣左')
Field.create(:name => '敵陣右')
Field.create(:name => '敵陣左')

Style.destroy_all
Style.create(:name => '攻め')
Style.create(:name => '守り')
Style.create(:name => 'バランス')
Style.create(:name => 'その他')

GameType.destroy_all
GameType.create(:name => '練習')
GameType.create(:name => '大会')
GameType.create(:name => '指導')

GameCount.destroy_all
GameCount.create(:name => '１試合目')
GameCount.create(:name => '２試合目')
GameCount.create(:name => '３試合目')
GameCount.create(:name => '４試合目')
GameCount.create(:name => '５試合目')
GameCount.create(:name => '６試合目')
GameCount.create(:name => '７試合目')
GameCount.create(:name => '８試合目')
GameCount.create(:name => '９試合目')

Grade.destroy_all
Grade.create(:name => 'A')
Grade.create(:name => 'B')
Grade.create(:name => 'C')
Grade.create(:name => 'D')
Grade.create(:name => 'E')
Grade.create(:name => 'F')
Grade.create(:name => 'G')
Grade.create(:name => '小学生')
Grade.create(:name => '中学生')
Grade.create(:name => '高校生')
Grade.create(:name => '大学生')
Grade.create(:name => 'シニア')
Grade.create(:name => 'ねんりん')

Karutum.destroy_all
Karutum.create(:waka => 'あきのたの かりほのいほの とまをあらみ わがころもでは つゆにぬれつつ', :waka_kanji => '秋の田の かりほの庵の 苫をあらみ わが衣手は 露にぬれつつ')
Karutum.create(:waka => 'はるすぎて なつきにけらし しろたへの ころもほすてふ あまのかぐやま', :waka_kanji => '春すぎて 夏来にけらし 白妙の 衣ほすてふ 天の香具山')
Karutum.create(:waka => 'あしびきの やまどりのをの しだりをの ながながしよを ひとりかもねむ', :waka_kanji => 'あしびきの 山鳥の尾の しだり尾の ながながし夜を ひとりかも寝む')
Karutum.create(:waka => 'たごのうらに うちいでてみれば しろたへの ふじのたかねに ゆきはふりつつ', :waka_kanji => '田子の浦に うち出でてみれば 白妙の 富士のたかねに 雪は降りつつ')
Karutum.create(:waka => 'おくやまに もみぢふみわけ なくしかの こゑきくときぞ あきはかなしき', :waka_kanji => '奥山に 紅葉踏み分け 鳴く鹿の 声聞くときぞ 秋は悲しき')
Karutum.create(:waka => 'かささぎの わたせるはしに おくしもの しろきをみれば よぞふけにける', :waka_kanji => '鵲の 渡せる橋に 置く霜の 白きを見れば 夜ぞふけにける')
Karutum.create(:waka => 'あまのはら ふりさけみれば かすがなる みかさのやまに いでしつきかも', :waka_kanji => '天の原 ふりさけ見れば 春日なる 三笠の山に 出でし月かも')
Karutum.create(:waka => 'わがいほは みやこのたつみ しかぞすむ よをうぢやまと ひとはいふなり', :waka_kanji => 'わが庵は 都のたつみ しかぞすむ 世をうぢ山と 人はいふなり')
Karutum.create(:waka => 'はなのいろは うつりにけりな いたづらに わがみよにふる ながめせしまに', :waka_kanji => '花の色は 移りにけりな いたづらに 我身世にふる ながめせしまに')
Karutum.create(:waka => 'これやこの ゆくもかへるも わかれては しるもしらぬも あふさかのせき', :waka_kanji => 'これやこの 行くも帰るも 別れては 知るも知らぬも あふ坂の関')
Karutum.create(:waka => 'わたのはら やそしまかけて こぎいでぬと ひとにはつげよ あまのつりぶね', :waka_kanji => 'わたの原 八十島かけて 漕き出でぬと 人には告げよ あまのつりぶね')
Karutum.create(:waka => 'あまつかぜ くものかよひぢ ふきとぢよ をとめのすがた しばしとどめむ', :waka_kanji => '天つ風 雲のかよひ路 吹きとぢよ 乙女の姿 しばしとどめむ')
Karutum.create(:waka => 'つくばねの みねよりおつる みなのがは こひぞつもりて ふちとなりぬる', :waka_kanji => '筑波嶺の みねより落つる みなの川 恋ぞつもりて 淵となりぬる')
Karutum.create(:waka => 'みちのくの しのぶもぢずり たれゆゑに みだれそめにし われならなくに', :waka_kanji => '陸奥の しのぶもぢずり 誰ゆゑに 乱れそめにし 我ならなくに')
Karutum.create(:waka => 'きみがため はるののにいでて わかなつむ わがころもでに ゆきはふりつつ', :waka_kanji => '君がため 春の野にいでて 若菜摘む わが衣手に 雪は降りつつ')
Karutum.create(:waka => 'たちわかれ いなばのやまの みねにおふる まつとしきかば いまかへりこむ', :waka_kanji => '立ち別れ いなばの山の 峰に生ふる まつとし聞かば 今帰り来む')
Karutum.create(:waka => 'ちはやぶる かみよもきかず たつたがは からくれなゐに みづくくるとは', :waka_kanji => 'ちはやぶる 神代もきかず 竜田川 からくれなゐに 水くくるとは')
Karutum.create(:waka => 'すみのえの きしによるなみ よるさへや ゆめのかよひぢ ひとめよくらむ', :waka_kanji => '住の江の 岸に寄る波 よるさへや 夢のかよひ路 人目よくらむ')
Karutum.create(:waka => 'なにはがた みじかきあしの ふしのまも あはでこのよを すぐしてよとや', :waka_kanji => '難波潟 短かき蘆の 節の間も 逢はでこの世を 過ぐしてよとや')
Karutum.create(:waka => 'わびぬれば いまはたおなじ なにはなる みをつくしても あはむとぞおもふ', :waka_kanji => 'わびぬれば 今はた同じ 難波なる 身をつくしても 逢はむとぞ思ふ')
Karutum.create(:waka => 'いまこむと いひしばかりに ながつきの ありあけのつきを まちいでつるかな', :waka_kanji => '今来むと いひしばかりに 長月の 有明の月を 待ち出でつるかな')
Karutum.create(:waka => 'ふくからに あきのくさきの しをるれば むべやまかぜを あらしといふらむ', :waka_kanji => '吹くからに 秋の草木の しをるれば むべ山風を あらしといふらむ')
Karutum.create(:waka => 'つきみれば ちぢにものこそ かなしけれ わがみひとつの あきにはあらねど', :waka_kanji => '月見れば ちぢに物こそ 悲しけれ わが身ひとつの 秋にはあらねど')
Karutum.create(:waka => 'このたびは ぬさもとりあへず たむけやま もみぢのにしき かみのまにまに', :waka_kanji => 'このたびは ぬさもとりあへず 手向山 紅葉のにしき 神のまにまに')
Karutum.create(:waka => 'なにしおはば あふさかやまの さねかづら ひとにしられで くるよしもがな', :waka_kanji => '名にし負はば 逢坂山の さねかづら 人に知られで くるよしもがな')
Karutum.create(:waka => 'おぐ（をぐ）らやま みねのもみぢば こころあらば いまひとたびの みゆきまたなむ', :waka_kanji => '小倉山 峰の紅葉ば 心あらば 今ひとたびの みゆき待たなむ')
Karutum.create(:waka => 'みかのはら わきてながるる いづみがは いつみきとてか こひしかるらむ', :waka_kanji => 'みかの原 わきて流るる いづみ川 いつ見きとてか 恋しかるらむ')
Karutum.create(:waka => 'やまざとは ふゆぞさびしさ まさりける ひとめもくさも かれぬとおもへば', :waka_kanji => '山里は 冬ぞさびしさ まさりける 人目も草も かれぬと思へば')
Karutum.create(:waka => 'こころあてに をらばやをらむ はつしもの おきまどはせる しらぎくのはな', :waka_kanji => '心あてに 折らばや折らむ 初霜の 置きまどはせる 白菊の花')
Karutum.create(:waka => 'ありあけの つれなくみえし わかれより あかつきばかり うきものはなし', :waka_kanji => '有明の つれなく見えし 別れより 暁ばかり 憂きものはなし')
Karutum.create(:waka => 'あさぼらけ ありあけのつきと みるまでに よしののさとに ふれるしらゆき', :waka_kanji => '朝ぼらけ 有明の月と 見るまでに 吉野の里に 降れる白雪')
Karutum.create(:waka => 'やまがはに かぜのかけたる しがらみは ながれもあへぬ もみぢなりけり', :waka_kanji => '山川に 風のかけたる しがらみは 流れもあへぬ 紅葉なりけり')
Karutum.create(:waka => 'ひさかたの ひかりのどけき はるのひに しづこころなく はなのちるらむ', :waka_kanji => '久方の 光のどけき 春の日に しづ心なく 花の散るらむ')
Karutum.create(:waka => 'たれをかも しるひとにせむ たかさごの まつもむかしの ともならなくに', :waka_kanji => '誰をかも 知る人にせむ 高砂の 松も昔の 友ならなくに')
Karutum.create(:waka => 'ひとはいさ こころもしらず ふるさとは はなぞむかしの かににほひける', :waka_kanji => '人はいさ 心も知らず ふるさとは 花ぞ昔の 香ににほひける')
Karutum.create(:waka => 'なつのよは まだよひながら あけぬるを くものいづこに つきやどるらむ', :waka_kanji => '夏の夜は まだ宵ながら 明けぬるを 雲のいづこに 月宿るらむ')
Karutum.create(:waka => 'しらつゆに かぜのふきしく あきののは つらぬきとめぬ たまぞちりける', :waka_kanji => '白露に 風の吹きしく 秋の野は つらぬきとめぬ 玉ぞ散りける')
Karutum.create(:waka => 'わすらるる みをばおもはず ちかひてし ひとのいのちの をしくもあるかな', :waka_kanji => ' 忘らるる 身をば思はず 誓ひてし 人の命の 惜しくもあるかな')
Karutum.create(:waka => 'あさぢふの をののしのはら しのぶれど あまりてなどか ひとのこひしき', :waka_kanji => '浅茅生の 小野の篠原 しのぶれど あまりてなどか 人の恋しき')
Karutum.create(:waka => 'しのぶれど いろにいでにけり わがこひは ものやおもふと ひとのとふまで', :waka_kanji => '忍ぶれど 色に出でにけり わが恋は 物や思ふと 人の問ふまで')
Karutum.create(:waka => 'こひすてふ わがなはまだき たちにけり ひとしれずこそ おもひそめしか', :waka_kanji => '恋すてふ わが名はまだき 立ちにけり 人知れずこそ 思ひそめしか')
Karutum.create(:waka => 'ちぎりきな かたみにそでを しぼりつつ すゑのまつやま なみこさじとは', :waka_kanji => '契りきな かたみに袖を しぼりつつ 末の松山 波こさじとは')
Karutum.create(:waka => 'あひみての のちのこころに くらぶれば むかしはものを おもはざりけり', :waka_kanji => '逢ひ見ての 後の心に くらぶれば 昔は物を 思はざりけり')
Karutum.create(:waka => 'おおこ（あふこ）との たえてしなくば なかなかに ひとをもみをも うらみざらまし', :waka_kanji => '逢ふことの 絶えてしなくば なかなかに 人をも身をも 恨みざらまし')
Karutum.create(:waka => 'あはれとも いふべきひとは おもほえで みのいたづらに なりぬべきかな', :waka_kanji => '哀れとも いふべき人は 思ほえで 身のいたづらに なりぬべきかな')
Karutum.create(:waka => 'ゆらのとを わたるふなびと かぢをたえ ゆくへもしらぬ こひのみちかな', :waka_kanji => '由良の門を 渡る舟人 かぢを絶え ゆくへも知らぬ 恋の道かな')
Karutum.create(:waka => 'やへむぐら しげれるやどの さびしきに ひとこそみえね あきはきにけり', :waka_kanji => '八重むぐら しげれる宿の さびしきに 人こそ見えね 秋は来にけり')
Karutum.create(:waka => 'かぜをいたみ いはうつなみの おのれのみ くだけてものを おもふころかな', :waka_kanji => '風をいたみ 岩うつ波の おのれのみ くだけて物を 思ふころかな')
Karutum.create(:waka => 'みかきもり ゑじのたくひの よるはもえて ひるはきえつつ ものをこそおもへ', :waka_kanji => 'みかきもり 衛士のたく火の 夜はもえ 昼は消えつつ 物をこそ思へ')
Karutum.create(:waka => 'きみがため おしからざりし いのちさへ ながくもがなと おもひけるかな', :waka_kanji => '君がため 惜しからざりし 命さへ 長くもがなと 思ひけるかな')
Karutum.create(:waka => 'かくとだに えやはいぶきの さしもぐさ さしもしらじな もゆるおもひを', :waka_kanji => 'かくとだに えやはいぶきの さしも草 さしもしらじな 燃ゆる思ひを')
Karutum.create(:waka => 'あけぬれば くるるものとは しりながら なほうらめしき あさぼらけかな', :waka_kanji => '明けぬれば 暮るるものとは 知りながら なほ恨めしき 朝ぼらけかな')
Karutum.create(:waka => 'なげきつつ ひとりぬるよの あくるまは いかにひさしき ものとかはしる', :waka_kanji => '嘆きつつ ひとり寝る夜の 明くる間は いかに久しき ものとかは知る')
Karutum.create(:waka => 'わすれじの ゆくすゑまでは かたければ けふをかぎりの いのちともがな', :waka_kanji => '忘れじの 行末までは かたければ 今日を限りの 命ともがな')
Karutum.create(:waka => 'たきのおとは たえてひさしく なりぬれど なこそながれて なほきこえけれ', :waka_kanji => '滝の音は 絶えて久しく なりぬれど 名こそ流れて なほ聞えけれ')
Karutum.create(:waka => 'あらざらむ このよのほかの おもひでに いまひとたびの あふこともがな', :waka_kanji => 'あらざらむ この世のほかの 思ひ出に いまひとたびの 逢ふこともがな')
Karutum.create(:waka => 'めぐりあひて みしやそれとも わかぬまに くもがくれにし よはのつきかな', :waka_kanji => 'めぐり逢ひて 見しやそれとも わかぬ間に 雲隠れにし 夜半の月かな')
Karutum.create(:waka => 'ありまやま ゐなのささはら かぜふけば いでそよひとを わすれやはする', :waka_kanji => '有馬山 猪名の笹原 風吹けば いでそよ人を 忘れやはする')
Karutum.create(:waka => 'やすらはで ねなましものを さよふけて かたぶくまでの つきをみしかな', :waka_kanji => 'やすらはで 寝なましものを 小夜更けて かたぶくまでの 月を見しかな')
Karutum.create(:waka => 'おおえ（おほえ）やま いくののみちの とほければ まだふみもみず あまのはしだて', :waka_kanji => '大江山 いく野の道の 遠ければ まだふみも見ず 天の橋立')
Karutum.create(:waka => 'いにしへの ならのみやこの やへざくら けふここのへに にほひぬるかな', :waka_kanji => 'いにしへの 奈良の都の 八重桜 けふ九重に にほひぬるかな')
Karutum.create(:waka => 'よをこめて とりのそらねは はかるとも よにあふさかの せきはゆるさじ', :waka_kanji => '夜をこめて 鳥の空音は はかるとも よに逢坂の 関はゆるさじ')
Karutum.create(:waka => 'いまはただ おもひたえなむ とばかりを ひとづてならで いふよしもがな', :waka_kanji => '今はただ 思ひ絶えなむ とばかりを 人づてならで いふよしもがな')
Karutum.create(:waka => 'あさぼらけ うじのかわぎり たえだえに あらはれわたる せぜのあじろぎ', :waka_kanji => '朝ぼらけ 宇治の川霧 たえだえに あらはれわたる 瀬々の網代木')
Karutum.create(:waka => 'うらみわび ほさぬそでだに あるものを こひにくちなむ なこそをしけれ', :waka_kanji => '恨みわび ほさぬ袖だに あるものを 恋に朽ちなむ 名こそ惜しけれ')
Karutum.create(:waka => 'もろともに あはれとおもへ やまざくら はなよりほかに しるひともなし', :waka_kanji => 'もろともに あはれと思へ 山桜 花よりほかに 知る人もなし')
Karutum.create(:waka => 'はるのよの ゆめばかりなる たまくらに かひなくたたむ なこそをしけれ', :waka_kanji => '春の夜の 夢ばかりなる 手枕に かひなく立たむ 名こそをしけれ')
Karutum.create(:waka => 'こころにも あらでうきよに ながらへば こひしかるべき よはのつきかな', :waka_kanji => '心にも あらでうき世に ながらへば 恋しかるべき 夜半の月かな')
Karutum.create(:waka => 'あらしふく みむろのやまの もみぢばは たつたのかはの にしきなりけり', :waka_kanji => '嵐吹く 三室の山の もみぢ葉は 竜田の川の 錦なりけり')
Karutum.create(:waka => 'さびしさに やどをたちいでて ながむれば いづこもおなじ あきのゆふぐれ', :waka_kanji => 'さびしさに 宿を立ち出でて ながむれば いづくも同じ 秋の夕暮')
Karutum.create(:waka => 'ゆふされば かどたのいなば おとづれて あしのまろやに あきかぜぞふく', :waka_kanji => '夕されば 門田の稲葉 おとづれて 蘆のまろやに 秋風ぞ吹く')
Karutum.create(:waka => 'おとにきく たかしのはまの あだなみは かけじやそでの ぬれもこそすれ', :waka_kanji => '音に聞く 高師の浜の あだ波は かけじや袖の ぬれもこそすれ')
Karutum.create(:waka => 'たかさごの をのへのさくら さきにけり とやまのかすみ たたずもあらなむ', :waka_kanji => '高砂の 尾上の桜 咲きにけり 外山の霞 立たずもあらなむ')
Karutum.create(:waka => 'うかりける ひとをはつせの やまおろしよ はげしかれとは いのらぬものを', :waka_kanji => '憂かりける 人を初瀬の 山おろしよ はげしかれとは 祈らぬものを')
Karutum.create(:waka => 'ちぎりおきし させもがつゆを いのちにて あはれことしの あきもいぬめり', :waka_kanji => '契りおきし させもが露を 命にて あはれ今年の 秋もいぬめり')
Karutum.create(:waka => 'わたのはら こぎいでてみれば ひさかたの くもゐにまがふ おきつしらなみ', :waka_kanji => 'わたの原 漕ぎ出でて見れば ひさかたの 雲居にまがふ 沖つ白波')
Karutum.create(:waka => 'せをはやみ いはにせかるる たきがはの われてもすゑに あはむとぞおもふ', :waka_kanji => '瀬を早み 岩にせかるる 滝川の われても末に 逢はむとぞ思ふ')
Karutum.create(:waka => 'あはぢしま かよふちどりの なくこゑに いくよねざめぬ すまのせきもり', :waka_kanji => '淡路島 かよふ千鳥の 鳴く声に 幾夜寝覚めぬ 須磨の関守')
Karutum.create(:waka => 'あきかぜに たなびくくもの たえまより もれいづるつきの かげのさやけさ', :waka_kanji => '秋風に たなびく雲の 絶え間より もれ出づる月の 影のさやけさ')
Karutum.create(:waka => 'ながからむ こころもしらず くろかみの みだれてけさは ものをこそおもへ', :waka_kanji => '長からむ 心も知らず 黒髪の 乱れて今朝は 物をこそ思へ')
Karutum.create(:waka => 'ほととぎす なきつるかたを ながむれば ただありあけの つきぞのこれる', :waka_kanji => 'ほととぎす 鳴きつる方を ながむれば ただ有明の 月ぞ残れる')
Karutum.create(:waka => 'おもひわび さてもいのちは あるものを うきにたへぬは なみだなりけり', :waka_kanji => '思ひわび さても命は あるものを 憂きに堪へぬは 涙なりけり')
Karutum.create(:waka => 'よのなかよ みちこそなけれ おもひいる やまのおくにも しかぞなくなる', :waka_kanji => '世の中よ 道こそなけれ 思ひ入る 山の奥にも 鹿ぞ鳴くなる')
Karutum.create(:waka => 'ながらへば またこのごろや しのばれむ うしとみしよぞ いまはこひしき', :waka_kanji => '長らへば またこのごろや しのばれむ 憂しと見し世ぞ 今は恋しき')
Karutum.create(:waka => 'よもすがら ものおもふころは あけやらで ねやのひまさへ つれなかりけり', :waka_kanji => '夜もすがら 物思ふころは 明けやらで 閨のひまさへ つれなかりけり')
Karutum.create(:waka => 'なげけとて つきやはものを おもはする かこちがほなる わがなみだかな', :waka_kanji => '嘆けとて 月やは物を 思はする かこち顔なる わが涙かな')
Karutum.create(:waka => 'むらさめの つゆもまだひぬ まきのはに きりたちのぼる あきのゆふぐれ', :waka_kanji => '村雨の 露もまだひぬ 槇の葉に 霧たちのぼる 秋の夕ぐれ')
Karutum.create(:waka => 'なにはえの あしのかりねの ひとよゆゑ みをつくしてや こひわたるべき', :waka_kanji => '難波江の 蘆のかりねの ひとよゆゑ みをつくしてや 恋ひわたるべき')
Karutum.create(:waka => 'たまのをよ たえなばたえね ながらへば しのぶることの よわりもぞする', :waka_kanji => '玉の緒よ 絶えなば絶えね ながらへば 忍ぶることの 弱りもぞする')
Karutum.create(:waka => 'みせばやな をじまのあまの そでだにも ぬれにぞぬれし いろはかはらず', :waka_kanji => '見せばやな 雄島のあまの 袖だにも 濡れにぞ濡れし 色はかはらず')
Karutum.create(:waka => 'きりぎりす なくやしもよの さむしろに ころもかたしき ひとりかもねむ', :waka_kanji => 'きりぎりす 鳴くや霜夜の さむしろに 衣片敷き ひとりかも寝む')
Karutum.create(:waka => 'わがそでは しほひにみえぬ おきのいしの ひとこそしらね かわくまもなし', :waka_kanji => 'わが袖は 潮干に見えぬ 沖の石の 人こそ知らね 乾く間もなし')
Karutum.create(:waka => 'よのなかは つねにもがもな なぎさこぐ あまのをぶねの つなでかなしも', :waka_kanji => '世の中は 常にもがもな 渚漕ぐ あまの小舟の 綱手かなしも')
Karutum.create(:waka => 'みよしのの やまのあきかぜ さよふけて ふるさとさむく ころもうつなり', :waka_kanji => 'み吉野の 山の秋風 小夜ふけて ふるさと寒く 衣うつなり')
Karutum.create(:waka => 'おおけ（おほけ）なく うきよのたみに おほふかな わがたつそまに すみぞめのそで', :waka_kanji => 'おほけなく うき世の民に おほふかな わがたつ杣に 墨染の袖')
Karutum.create(:waka => 'はなさそふ あらしのにはの ゆきならで ふりゆくものは わがみなりけり', :waka_kanji => '花さそふ 嵐の庭の 雪ならで ふりゆくものは わが身なりけり')
Karutum.create(:waka => 'こぬひとを まつほのうらの ゆふなぎに やくやもしほの みもこがれつつ', :waka_kanji => '来ぬ人を まつほの浦の 夕なぎに 焼くや藻塩の 身もこがれつつ')
Karutum.create(:waka => 'かぜそよぐ ならのをがはの ゆふぐれは みそぎぞなつの しるしなりける', :waka_kanji => '風そよぐ ならの小川の 夕暮は みそぎぞ夏の しるしなりける')
Karutum.create(:waka => 'ひともをし ひともうらめし あぢきなく よをおもふゆゑに ものおもふみは', :waka_kanji => '人もをし 人もうらめし あぢきなく 世を思ふゆゑに 物思ふ身は')
Karutum.create(:waka => 'ももしきや ふるきのきばの しのぶにも なほあまりある むかしなりけり', :waka_kanji => 'ももしきや 古き軒端の しのぶにも なほあまりある 昔なりけり')
